# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '公司新闻', 'verbose_name_plural': '公司新闻'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterField(
            model_name='message',
            name='contact_way',
            field=models.CharField(max_length=30, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.TextField(verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='新闻标题'),
        ),
        migrations.AlterField(
            model_name='position',
            name='duty',
            field=models.TextField(verbose_name='岗位职责'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=30, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='position',
            name='requirements',
            field=models.TextField(verbose_name='任职要求'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, storage=homepage.storage.OverwriteStorage(), upload_to='product_images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='introduction',
            field=models.TextField(verbose_name='产品简介'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
    ]
