# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170725_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
    ]
